[package]
  cjc-version = "1.0.5"
  name = "aho4cj"
  description = "Aho-Corasick 多模式字符串搜索库的仓颉实现"
  version = "0.1.0"
  target-dir = ""
  output-type = "static"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
