[package]
  cjc-version = "1.0.5"
  name = "aho_cangjie_benchmark"
  version = "0.1.0"
  output-type = "executable"
  compile-option = "-O2"
  override-compile-option = "-O2"

[dependencies]
  aho4cj = { path = "../.." }
